- column: event_timestamp
  description: Pub/Sub event timestamp
  mode: REQUIRED
  type: TIMESTAMP
- column: attributes
  description: Pub/Sub message attributes
  mode: NULLABLE
  type: MAP<STRING,STRING>
- column: payload
  description: Pub/Sub message payload
  mode: NULLABLE
  type: STRUCT
  subcolumns:
    - column: version
      description: Action Version
      mode: REQUIRED
      type: STRING
    - column: type
      description: Action Type
      mode: REQUIRED
      type: STRING
    - column: color
      description: Button Color
      mode: REQUIRED
      type: STRING
    - column: click
      description: Number times the button was clicked
      mode: REQUIRED
      type: INT64
